### ISSUE TITLE
Mozilla Firefox browser support

### ISSUE THREAD

**Issue by Kenrie19** [SimonStnn/pop-a-loon#72]

**Comment by SimonStnn** [comment]
The [mozilla/webextension-polyfill](https://github.com/mozilla/webextension-polyfill) npm package can be used for cross platform web extension development.

This is beeing implemented in the [`feature/mozilla-support`](https://github.com/SimonStnn/pop-a-loon/tree/feature/mozilla-support) branch.

**Comment by SimonStnn** [comment]
Pop-a-loon is now supported on firefox as of https://github.com/SimonStnn/pop-a-loon/releases/tag/v1.6.3.
